[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts'
]
solc = '0.8.13'

# See more config options https://github.com/gakonst/foundry/tree/master/config