[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts',
    '@solmate/=lib/solmate/src/
]

# See more config options https://github.com/gakonst/foundry/tree/master/config